name: test

on:
  push:
    branches:
      - main

jobs:
  test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo the message
        run: echo "Hello World"
